apiVersion: v1
kind: Secret
metadata:
  name: weather-secrets
  namespace: weather-app
type: Opaque
stringData:
  WEATHER_API_KEY: "c53aa81dcc0e8121e71798348bfd690c"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"
  DATABASE_URL: "postgresql://admin:admin@postgres-service:5432/postgres"
